### ISSUE TITLE
Expected value, got 'undefined' in command IMGUI_BUTTON your mod isnt working

### ISSUE THREAD

**Issue by SDUBZ** [Zenbeau/ImGuiRedux_Cleo_GTA_SA_DE#1]
[cleo_redux.log](https://github.com/Zenbeau/ImGuiRedux_Cleo_GTA_SA_DE/files/13599478/cleo_redux.log)
mod menu doesnt show anymore
even with the one that ships with cleo seems not to work

**Comment by Zenbeau** [comment]
works fine if you use the old ImGuiReduxWin64.cleo plugin which i provided. if you use the new one, it gets messed up. I think Grinch updated ImGuiRedux so i'm supposed to update it accordingly with him to make it work with the new version
